# Generated by Django 2.0.3 on 2019-01-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_myuser_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
