# Generated by Django 2.0.3 on 2019-01-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_myuser_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='lastname',
        ),
    ]
