# Generated by Django 2.0.3 on 2019-01-26 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190126_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 1, 26, 13, 37, 28, 362891), max_length=8),
        ),
    ]
