# Generated by Django 2.0.3 on 2019-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190126_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(auto_now_add=True, max_length=8),
        ),
    ]
